mapyEwakuacyjne/mapy/urls.py
from django.urls import path, include
from . import views


app_name = "mapy"
urlpatterns = [
    path('obrazy/', views.lista_obrazow_tla, name='lista_obrazow_tla'),
    path('trasa/nowa/<int:obraz_id>/', views.stworz_trase, name='stworz_trase'),
    path('trasa/edytuj/<int:trasa_id>/', views.edytuj_trase, name='edytuj_trase'),
    path('punkt/usun/<int:punkt_id>/', views.usun_punkt, name='usun_punkt'),
    path('moje-trasy/', views.lista_tras_uzytkownika, name='lista_tras_uzytkownika'),
    path('', views.lista_obrazow_tla, name='index'),
]

mapyEwakuacyjne/mysite/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from mapy import views as mapy_views
from rest_framework.authtoken import views

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Trasy API",
      default_version='v1',
      description="API do zarządzania trasami i ich punktami",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="k_godlewska@interia.pl"),
      license=openapi.License(name="License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('', include('mapy.urls')),

    path('account/rejestracja/', mapy_views.rejestracja, name='rejestracja'),
    path('account/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),

    path('api/', include('mapy.api_urls'), name='mapy_api'),
    path('api/auth-token/', views.obtain_auth_token, name='api_auth_token'),

    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mapyEwakuacyjne/templates/account_profile.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
Account Profile Page
{% endblock %}

mapyEwakuacyjne/templates/base.html
{% load static %}
{% load tailwind_cli %}
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}Moja Aplikacja Map{% endblock %}</title>

    {% tailwind_css %} {# Wstaw CSS Tailwind #}

    <style>
        body {
            background-image: url("/media/obrazki/tloSzlaki.jpg"); 
            background-position:  center 30;
        }

        button{
            color: #0b0f1d;
            background-color: #B49C90;
            font-weight: 500;
            font-size: 0.875rem;
            line-height: 1.25rem;
            padding: 0.625rem 1.25rem; 
            margin-right: 0.5rem;
            margin-bottom: 0.5rem;
            text-align: center;
            border: none;
            cursor: pointer;
        }

        button:hover {
            background-color: #c49b6c; 
            transition-duration: 100ms;
        }

        .red-yellow-button {
            color: #0b0f1d;
            background-image: linear-gradient(to right, #78350f, #c49b6c, #B49C90);
            font-weight: 500;
            font-size: 0.875rem;
            line-height: 1.25rem;
            padding: 0.625rem 1.25rem; 
            margin-right: 0.5rem;
            margin-bottom: 0.5rem;
            text-align: center;
            border: none;
            cursor: pointer;
        }

        .red-yellow-button:hover {
            background-image: linear-gradient(to left, #c49b6c, #B49C90, #B49C90); 
            transition-duration: 200ms;
        }

        .red-yellow-button:focus {
            outline: none; 
            box-shadow: 0 0 0 4px rgba(248, 113, 113, 0.5);
        }

        .dark .red-yellow-button:focus {
            box-shadow: 0 0 0 4px rgba(248, 113, 113, 0.7);
        }
    </style>
    
</head>
<body>
    <header class="flex flex-col py-4 m-4 bg-amber-50/50 items-center justify-center rounded-lg shadow-md">
        <nav>
            <h1 class="items-center text-center"><a href="{% url 'mapy:index' %}" class="text-3xl p-4 hover-bg-amber-50">Edytor Tras</a></h1> {# Link do strony głównej aplikacji #}
            <div class="flex p-4 m-4 items-center justify-betwee w-full">
                <button class="red-yellow-button rounded-full"><a href="{% url 'mapy:lista_obrazow_tla' %}">Wybierz Obraz Tła</a></button>

                {# Linki zależne od stanu zalogowania użytkownika #}
                {% if user.is_authenticated %}
                    <button class="bg-stone-50/50 bg-50 rounded-full cursor-pointer ml-4 py-2 px-4"><a href="{% url 'mapy:lista_tras_uzytkownika' %}">Moje Trasy</a></button>
                    <h3 class="py-2 px-4">Witaj, {{ user.username }}!</h3>
                    <div>
                        <form id="logout-form" action="{% url 'logout' %}" method="post" style="display: inline;">
                             {% csrf_token %}
                             <button type="submit" class="red-yellow-button rounded-full">Wyloguj</button>
                         </form>
                    </div>
                {% else %}
                    <button class="red-yellow-button rounded-full"><a href="{% url 'login' %}">Zaloguj</a></button>
                    <button class="red-yellow-button rounded-full"><a href="{% url 'rejestracja' %}">Zarejestruj</a></button>
                {% endif %}
            </div>
        </nav>
    </header>

    <main class="flex flex-col py-10 m-4 bg-stone-50/50 gap-4">
        {% block content %}
            <p>Witaj w aplikacji!</p>
        {% endblock %}
    </main>

    
    <footer class= "bg-amber-50/50 flex items-center justify-center py-10 overline m-4">
        <p class="text-center">&copy; {% now "Y" %} Kamila Godlewska</p>
    </footer>

</body>
</html>

mapyEwakuacyjne/templates/index.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
Django Registration Template Page
{% endblock %}